<a href="https://colab.research.google.com/github/Nikolay-son-Yura/python/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd 
import numpy as np 
import random
 
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})

data.head()

  whoAmI
0  robot
1  human
2  robot
3  human
4  human

In [11]:
pd.get_dummies(data['whoAmI'])

    human  robot
0       0      1
1       1      0
2       0      1
3       1      0
4       1      0
5       0      1
6       1      0
7       0      1
8       1      0
9       1      0
10      0      1
11      0      1
12      1      0
13      0      1
14      1      0
15      1      0
16      0      1
17      0      1
18      0      1
19      1      0

In [12]:
data['tmp'] = 1
data.set_index([data.index, 'whoAmI'], inplace=True)
data = data.unstack(level=-1, fill_value = 0).astype(int)
data.columns = data.columns.droplevel()
data.columns.name = None
print(data)

    human  robot
0       0      1
1       1      0
2       0      1
3       1      0
4       1      0
5       0      1
6       1      0
7       0      1
8       1      0
9       1      0
10      0      1
11      0      1
12      1      0
13      0      1
14      1      0
15      1      0
16      0      1
17      0      1
18      0      1
19      1      0